name: Run Selenium Tests and Deploy Allure Report

# Workflow is triggered manually using 'workflow_dispatch'
on:
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      ALLURE_HISTORY_ZIP: history.zip
      CHROMEDRIVER_VERSION: 128.0.6613.137
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    # Install Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    # Install ChromeDriver
    - name: Install ChromeDriver
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        cd chromedriver-linux64
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    # Set up Allure
    - name: Install Allure
      run: |
        ALLURE_VERSION=$(curl -sS https://api.github.com/repos/allure-framework/allure2/releases/latest | jq -r .tag_name)
        wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-commandline-${ALLURE_VERSION}.zip
        unzip allure-commandline-${ALLURE_VERSION}.zip
        sudo mv allure-${ALLURE_VERSION}/bin/allure /usr/local/bin/
        sudo chmod +x /usr/local/bin/allure

    # Run the tests
    - name: Run Selenium tests
      run: mvn clean install -DexecutionType=chrome-headless

    # Download Allure history from Netlify (if exists)
    - name: Download Allure history from Netlify (if exists)
      run: |
        NETLIFY_HISTORY_URL=https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/files/history.zip
        curl --fail -o $ALLURE_HISTORY_ZIP $NETLIFY_HISTORY_URL || echo "No history.zip found"
        if [ -f "$ALLURE_HISTORY_ZIP" ]; then
          unzip $ALLURE_HISTORY_ZIP
          mv history target/allure-results/history
        fi

    # Generate Allure report
    - name: Generate Allure report
      run: |
        allure generate target/allure-results --clean -o allure-report

    # Zip the Allure history for future reference
    - name: Zip Allure history
      run: |
        cd allure-report/history
        zip -r $ALLURE_HISTORY_ZIP ./*

    # Upload history.zip to Netlify for future test runs
    - name: Upload Allure history to Netlify
      run: |
        curl -X POST -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
        --upload-file $ALLURE_HISTORY_ZIP \
        https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/files/history.zip

    # Deploy the Allure report to Netlify
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1
      with:
        publish-dir: ./allure-report
        production-deploy: true
        deploy-message: "Deploying Allure Report"
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}

    # Post Allure report link as a comment on pull request or push
    - name: Post Netlify URL as comment
      if: github.event_name == 'pull_request'
      run: |
        REPORT_URL=$(curl --silent https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID | jq -r .url)
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -X POST \
          -d "{\"body\": \"Allure Report deployed: $REPORT_URL\"}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
